### PR TITLE
feat(ios): added basic UI in MSM Benchmark

### PR DESCRIPTION
**Pull request by FoodChain1028**
# Integrating MSM benchmark on IOS 

> we are aiming to integrate the previous work into IOS Example project

### iOS
- [x] Design the way to illustrate the benchmark of this
    - [x] A swift file that maps all algorithm from uniffi to swift. <u>Make it the only file we need to change if added a new algorithm.</u>
    - [x] A swift file for UI
        - [x] A component to show the integrated algorithm
        - [x] Rendering the mapped algorithm and wrapped it into components
        - [x] A button component for "Generating Benchmarks"
    - [x] A swift file for report generating logic
        - [x] show a table for (`num_msm`)
            | Algorithm   | Avg Timing | Compare to baseline <br>(arkwork-msm)</br> |
            | ----------- | --------------- |:------------------------------------------:|
            | arkworks-msm | in ms           |                     -                      |
            | Algo. A     | in ms           |                    in %                    |
            | Algo. B     | in ms           |                    in %                    |

        - [x] [Backlog] show a figure 

## Link 

- [report](https://hackmd.io/OGYdUUsoQzump7uLB5YqKg)

### CODE REVIEW

**Comment by moven0831** [comment]
|                                   |                                                        laptop<br>(Rust test)                                                         |                                                        laptop<br>(Swift test)                                                         |                                                              iOS Simulator<br>[Demo Video](https://youtu.be/c0FrjWPrqxY)                                                              |                                                                 iPhone<br>[Demo Video](https://youtu.be/l-8MvycDTHY)                                                                  |
|:---------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------:|
|  Timing<br>(Single Arkworks MSM)   |                                                               0.33 ms                                                                |                                                                0.37 ms                                                                |                                                                 0.31 ms                                                                 |                                                                 0.27 ms                                                                 |
|            Device Spec            |                                                               M2 chip                                                                |                                                                M2 chip                                                                |                                                                 M2 chip                                                                 |                                                      iPhone 14 Pro<br>(A16 Bionic)                                                      |
| Screenshots<br>(Click to enlarge) | [](https://hackmd.io/_uploads/Sy1l9Mmh6.png) | [](https://hackmd.io/_uploads/rkEl5G736.png) | [](https://hackmd.io/_uploads/HJttqMQha.png) | []


The report of this PR can be found here: https://hackmd.io/@FoodChain/rk3iyg3da

**Review by oskarth — COMMENTED** [review]
Thank you! Looks good. Only thing is that CI is failing for iOS, not sure why.

(Android fails but this is expected, iOS should work in main though)

**Comment by moven0831** [comment]
I've re-run the workflow for the failed tests, and the part that previously stalled (circom installation) has successfully completed this time. I'll send a review request once the iOS test finishes.

**Comment by moven0831** [comment]
Closed #21

**Pull request merged**
